const locations = [
    {label:'اراک',value:'اراک'},
    {label:'اردبیل',value:'اردبیل'},
    {label:'تبریز',value:'تبریز'},
    {label:'اصفهان',value:'اصفهان'},
    {label:'اهواز',value:'اهواز'},
    {label:'ایلام',value:'ایلام'},
    {label:'بجنورد',value:'بجنورد'},
    {label:'بجنورد',value:'بجنورد'},
    {label:'بندرعباس',value:'بندرعباس'},
    {label:'بوشهر',value:'بوشهر'},
    {label:'بیرجند',value:'بیرجند'},
    {label:'ارومیه',value:'ارومیه'},
    {label:'تهران',value:'تهران'},
    {label:'خرم آباد',value:'خرم آباد'},
    {label:'رشت',value:'رشت'},
    {label:'زاهدان',value:'زاهدان'},
    {label:'زنجان',value:'زنجان'},
    {label:'ساری',value:'ساری'},
    {label:'سمنان',value:'سمنان'},
    {label:'سنندج',value:'سنندج'},
    {label:'شهرکرد',value:'شهرکرد'},
    {label:'شیراز',value:'شیراز'},
    {label:'قزوین',value:'قزوین'},
    {label:'قم',value:'قم'},
    {label:'کرج',value:'کرج'},
    {label:'کرمان',value:'کرمان'},
    {label:'کرمانشاه',value:'کرمانشاه'},
    {label:'گرگان',value:'گرگان'},
    {label:'مشهد',value:'مشهد'},
    {label:'همدان',value:'همدان'},
    {label:'یاسوج',value:'یاسوج'},    
    {label:'یزد',value:'یزد'},    
]

export default locations;